language: c
script: ./scripts/travis-builds.sh
env:
    # full magenta kernel + user space builds
    - PROJECT=magenta-pc-x86-64
    - PROJECT=magenta-qemu-arm64
    - PROJECT=magenta-rpi3-arm64
    - PROJECT=magenta-hikey960-arm64
    - PROJECT=magenta-odroidc2-arm64

sudo: required
dist: trusty

cache:
    directories:
    - prebuilt/downloads
    - prebuilt/configs

notifications:
    irc:
        channels:
            - "chat.freenode.net#fuchsia-bot"
        skip_join: true
        use_notice: true
